### ISSUE TITLE
启动项目出错，编译SCSS/SASS出现了问题，求助

### ISSUE THREAD

**Issue by 0000rookie** [FarseaSH/hugo-theme-moments#11]
你好，我在使用时启动出现了错误，使用原版的hugo启动时，出现第一个错误，使用hugo拓展版第二个出现了新错误，错误如下。求助
![](https://bu.dusays.com/2023/03/14/640f5589b6b72.png)

**Comment by FarseaSH** [comment]
Hi 感谢你的使用。我这边使用的是hugo v0.85.0+extend版本，应该是正常的，不知道Hugo版本会不会造成一些差异。

在网上查了一下，一个可能的解决方案是：在`row.html`文件里，把这两行（8行9行）合并成一行

```
<div class="month-day">{{ .Date.Format "Jan 2"}}{{ if in (slice 1 21 31) .Date.Day}}st{{ else if in (slice 2 22)
                    .Date.Day}}nd{{ else if in (slice 3 23) .Date.Day}}rd{{ else }}th{{ end }}</div>
```

你可以尝试一下，如果还有问题，随时欢迎联系。

**Comment by 0000rookie** [comment]
我用了hugo v0.85.0+extend，没有发现问题，可能是新版不太兼容的样子，谢谢大佬的回答
