### ISSUE TITLE
期待：—使用Notion，结合Moments主题，免费、快速搭建短博文平台。即将发布。

### ISSUE THREAD

**Issue by beyondtop** [FarseaSH/hugo-theme-moments#20]
你好，请问这个新项目什么时候能发布？非常期待使用 notion来写短博文。

**Comment by beyondtop** [comment]
非常感谢，也不知道你用的什么联系方式，就留个E-mail：1070461593@qq.com吧，麻烦你了。

**Comment by wangyunzi** [comment]
我记得有一个博客就是notion结合hugo博客即时发布，作者可以看看那个

**Comment by FarseaSH** [comment]
@wangyunzi 好的，我去关注一下，谢谢啦

**Comment by invmv** [comment]
> 非常感谢，也不知道你用的什么联系方式，就留个E-mail：[1070461593@qq.com](mailto:1070461593@qq.com)吧，麻烦你了。

https://github.com/invmv/Notion-Hugo-theme-Moments
