### ISSUE TITLE
请问怎么将这个moments主题作为一个单页合并在stack主题中

### ISSUE THREAD

**Issue by chu2y** [FarseaSH/hugo-theme-moments#21]
hello，一直想找一个类似朋友圈的主题，看教程的时候看到别人博客中的moments，直接被你的这个主题惊艳到。我非常想把这个主题整合到现有的stack主题中，我参考了hugo相关论坛和其他博主说到的一些多主题结合的方法，尝试了一下，都没有成功，这个问题也困绕了我好多天，想向您请教一下如何整合moments。

**Comment by chu2y** [comment]
我使用了很蠢的办法(重新建了一个站，使用moments主题)实现了这个功能，不知道有没有更好的办法。
另外基于Hugo容器部署(hugomods/hugo:exts-0.124.1)，并使用moments主题时，发现了一个问题：
无法加载style-refractored.min.da6f8359e1fb68bf5bfd0fdc53b60eec7dcc241b0320ec57130952783dc4fdc0.css 的文件，看请求地址是localhost:1313，但是我已经在config文件中定义了baseURL(好像并没有起作用)。
后来在Hugo server 后加了--baseURL 参数强制指定地址才可以，不知道是不是hugo的bug。

**Comment by FarseaSH** [comment]
Hello，谢谢你对这款主题的关注~

不知道你对Hugo框架掌握多少？如果熟悉的话，我感觉应该是一个不难的事情。方便私信我一个你的联系方式么？可以私下聊一下。

**Comment by chu2y** [comment]
非常感谢您的回复。我的微信号是：   puup1L

**Comment by chu2y** [comment]
感谢您的回复  
我的邮箱是 chuzhaoyi@hotmail.com，微信是 puup1L 看您这边哪个方便
