### ISSUE TITLE
页面底部是否应该改为滚动时加载，而不是第一页第二页翻页？

### ISSUE THREAD

**Issue by xijaja** [FarseaSH/hugo-theme-moments#6]

**Comment by ZhaoZuohong** [comment]
附议

**Comment by FarseaSH** [comment]
谢谢你的建议，载入更多条目的逻辑我之后会做出改进，我也在找滚动加载技术上实现的方法～

但我自己也不是前端，相关技术不是很熟，如果你能提供解决方法甚至提交pull request，本人将感激不尽～

如果你有其它方面的需求、建议，随时欢迎提出～

**Comment by FarseaSH** [comment]
#8 已经支持

**Comment by xijaja** [comment]
我自学了 3 个月前端，打算回来写这个，重新打开这个议题，发现已经支持了！
🙏 感谢 @ZhaoZuohong

**Comment by ZhaoZuohong** [comment]
@xijaja ~~三月之期已到~~
